### ISSUE TITLE
Con respecto al curso

### ISSUE THREAD

**Issue by Nahuel-N** [pdep-utn-frd/presentacion-2021-Diego-Mamani#1]
Me interesa saber si lo de Coursera requiere conocimiento previo, o podes arrancar de cero.
Y el correo de la facu lo tenes que pedir en alguna secretaria?

**Comment by Diego-Mamani** [comment]
Hola. No se requiere conocimiento previo. Respecto al correo de la facu, lo tenés que solicitar al GESiN. Con el siguiente enlace vas a poder completar un formulario para generar tu mail y contraseña con dominio frd:

https://forms.office.com/Pages/ResponsePage.aspx?id=6Nx9Z9me9k2YUxVvA9aiWEAcrtMBK8ZIkeTmyfISpFNUNUJNM0NFODZZQjBBS0FENlFKOEZJQjVPUi4u
